// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGcFQ-J8fUZl5S3_L2zkanqUGdUnf3GMQ',
    appId: '1:379357790018:web:53b06b632902e11d80d2db',
    messagingSenderId: '379357790018',
    projectId: 'shineschedule-7b085',
    authDomain: 'shineschedule-7b085.firebaseapp.com',
    storageBucket: 'shineschedule-7b085.appspot.com',
    measurementId: 'G-81Z07FCYJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGWKKm8ytsvEiVoxCKPBPpZkX9tKP4Em0',
    appId: '1:379357790018:android:7ad64be949825e0780d2db',
    messagingSenderId: '379357790018',
    projectId: 'shineschedule-7b085',
    storageBucket: 'shineschedule-7b085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoFpOPxhVWRGsktP2Hp5QtIUI6I0ZAcoQ',
    appId: '1:379357790018:ios:869c3ad093c612e180d2db',
    messagingSenderId: '379357790018',
    projectId: 'shineschedule-7b085',
    storageBucket: 'shineschedule-7b085.appspot.com',
    androidClientId: '379357790018-b4pbin28ta1j5c0158opr09cb0bsfc7n.apps.googleusercontent.com',
    iosClientId: '379357790018-rbtu63gi8fu8f545skm5vatms7oifcu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shineSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoFpOPxhVWRGsktP2Hp5QtIUI6I0ZAcoQ',
    appId: '1:379357790018:ios:869c3ad093c612e180d2db',
    messagingSenderId: '379357790018',
    projectId: 'shineschedule-7b085',
    storageBucket: 'shineschedule-7b085.appspot.com',
    androidClientId: '379357790018-b4pbin28ta1j5c0158opr09cb0bsfc7n.apps.googleusercontent.com',
    iosClientId: '379357790018-rbtu63gi8fu8f545skm5vatms7oifcu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shineSchedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGcFQ-J8fUZl5S3_L2zkanqUGdUnf3GMQ',
    appId: '1:379357790018:web:df42e3099486cf3f80d2db',
    messagingSenderId: '379357790018',
    projectId: 'shineschedule-7b085',
    authDomain: 'shineschedule-7b085.firebaseapp.com',
    storageBucket: 'shineschedule-7b085.appspot.com',
    measurementId: 'G-F3ESN4F39K',
  );
}
