-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g 
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args 
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error 
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter 
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider 
-keepclassmembers class ai.deepar.ar.DeepAR { *; }
-keepclassmembers class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava { *; }
-keep class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava